#PBS -N mu_1.1052631578947363 
#PBS -q test 
#PBS -l nodes=1:ppn=1 
#PBS -l walltime=00:01:00:00 
#PBS -j o output.pbs 
#PBS -j e error.pbs 

echo Starting job $PBS_JOBID 
echo
echo PBS assigned me this node: 
cat $PBS_NODEFILE 
echo 
echo "Running ${job_name}" 
echo 
mpirun -np 1 /home/sr802/Programs/lammps-12Dec18/src/lmp_dexter -in input.lmp
echo 
echo "Job finished. PBS details are:" 
echo 
qstat -f ${PBS_JOBID} 
echo 
echo Finished at \`date\` 
